[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning - Firebase frontend config is meant to be public
  SECRETS_SCAN_ENABLED = "false"

# SPA routing redirects
[[redirects]]
  from = "/view/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/upload/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Scheduled function for auto-delete cleanup
[[schedules]]
  path = "netlify/functions/scheduled-cleanup.js"
  schedule = "@daily"

# Netlify plugins
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Comprehensive CSP that allows all Firebase services and required resources
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.gstatic.com https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://res.cloudinary.com https://*.cloudinary.com; connect-src 'self' https://*.googleapis.com https://*.gstatic.com https://api.cloudinary.com https://*.cloudinary.com https://*.netlify.app https://*.firebaseapp.com https://cdn.jsdelivr.net https://*.ingest.sentry.io https://*.ingest.us.sentry.io; media-src 'self' blob: data: https://res.cloudinary.com https://*.cloudinary.com; frame-src 'self' blob: https://res.cloudinary.com https://www.youtube.com https://www.youtube-nocookie.com https://player.vimeo.com; object-src 'self' blob:; worker-src 'self' blob:"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache main HTML
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Environment variables needed in Netlify dashboard:
# 
# IMPORTANT: Set SECRETS_SCAN_ENABLED = false in Netlify dashboard
# Firebase frontend config values are INTENTIONALLY PUBLIC
#
# Frontend Firebase Config:
# FIREBASE_API_KEY
# FIREBASE_AUTH_DOMAIN  
# FIREBASE_PROJECT_ID
# FIREBASE_STORAGE_BUCKET
# FIREBASE_MESSAGING_SENDER_ID
# FIREBASE_APP_ID
#
# Backend Function Config:
# FIREBASE_CLIENT_EMAIL  
# FIREBASE_PRIVATE_BASE_64_KEY (Base64 encoded private key)
#
# Cloudinary Config:
# CLOUDINARY_CLOUD_NAME
# CLOUDINARY_UPLOAD_PRESET
# CLOUDINARY_API_KEY (for scheduled cleanup function)
# CLOUDINARY_API_SECRET (for scheduled cleanup function)
#
# Security Config:
# SECRETS_SCAN_ENABLED = false
# CLOUDINARY_UPLOAD_PRESET